sudo: required
services:
- docker
language: python
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t cultclassik/rpilo .
# test image
- docker run cultclassik/rplio
# push image

- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG="armhf"
    docker tag cultclassik/rpilo cultclassik/rpilo:$TAG
    docker push cultclassik/rpilo:$TAG
    docker push cultclassik/rpilo
  fi

# TAG=$(grep "ENV MYSQL_VERSION" Dockerfile | awk 'NF>1{print $NF}')