sudo: required

language: python

services:
- docker

before_install:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t cultclassik/rpilo .
- docker images
# run and test image
- docker run -d --name=rpilo cultclassik/rpilo
- docker ps -a

script:
- docker exec rpilo python3 -m unittest discover
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- DREPO="cultclassik/rpilo"
- TAG="arm32v6"
- docker tag $DREPO $DREPO:$TAG
- docker push $DREPO:$TAG
- docker push $DREPO
