sudo: required

language: python

services:
- docker

before_install:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t cultclassik/rpilo .
# test image
- docker run -d --name=rpilo cultclassik/rpilo
- docker ps -a

script:
- docker exec rpilo python3 -m unittest discover

- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG="arm32v6"
    docker tag cultclassik/rpilo cultclassik/rpilo:$TAG
    docker push cultclassik/rpilo:$TAG
    docker push cultclassik/rpilo
  fi

# TAG=$(grep "ENV TAG_NAME" Dockerfile | awk 'NF>1{print $NF}')